name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: git clone https://github.com/twilio/authy-java
      - run:    git rev-parse HEAD
      - run: mvn test-compile -pl authy-java/. -am
      - run:      mvn -pl authy-java/. test -Dtest=com.authy.api.UserStatusTest#testToXML
      - run:      mvn -pl authy-java/. edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.authy.api.UserStatusTest#testToXML
